name: pyannote

files:
  - destination: files/pyannote-segmentation-3.0.bin
    source: https://github.com/marchellodev/zvuk_models/raw/67846f822b9926bdf3552bcbe65cd366ff0420b7/pyannote/pyannote-segmentation-3.0.bin
    type: url
    size: 5.91

  - destination: files/wespeaker-voxceleb-resnet34-LM.bin
    source: https://huggingface.co/pyannote/wespeaker-voxceleb-resnet34-LM/resolve/main/pytorch_model.bin?download=true
    type: url
    size: 26.6
